const framesUntilHealed = 60;
const transmissionRate = 0.1;
const numPeople = 300;
const screenWidth = 400, screenHeight = 400;
const numPeopleStartingImmune = 0;
const transmissionRange = 15;
const immuneFrames = 999999999;
const deathRateIfTreated = 0.2;
const deathRateIfNotTreated = 0.5;
const probOfSeriouslyIll = 0.25;
const mouseTransmissionRange = 30;
const numHospitalBeds = numPeople * 0.05;